codecov:
  ci:
    - "circleci.com"

coverage:
  # TODO: Use better coverage configs after adding better unit test coverage
  status:
    patch:
      default:
        target: 50%
        threshold: 0%
    project:
      default:
        target: 50%
        threshold: 0%
